networks:
  reviewer-service-net:
    driver: bridge

volumes:
  postgres_data:

services:
  postgres:
    image: postgres:17.5
    container_name: postgres
    env_file:
      - config/prod.env
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - reviewer-service-net

  migrate:
    build: .
    container_name: migrate
    depends_on:
      postgres:
        condition: service_healthy
    entrypoint: ["/app/migrate"]
    command: ["--config_path=config/prod.env", "--migration_path=database/migrations"]
    networks:
      - reviewer-service-net
    restart: "no"

  reviewer-service:
    build: .
    container_name: reviewer-service
    ports:
      - "8080:8080"
    depends_on:
      migrate:
        condition: service_completed_successfully
    entrypoint: ["/app/reviewer-service"]
    command: ["--config_path=config/prod.env"]
    networks:
      - reviewer-service-net
