networks:
  reviewer-service-net:
    driver: bridge

volumes:
  postgres_data:

services:
  postgres:
    image: postgres:17.5
    container_name: postgres
    env_file:
      - config/prod.env
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - reviewer-service-net

  migrate:
    build:
      context: .
      dockerfile: Dockerfile
    image: reviewer-service
    container_name: migrate
    depends_on:
      postgres:
        condition: service_healthy
    entrypoint: ["/app/migrate"]
    command: ["--config_path=config/prod.env", "--migration_path=database/migrations"]
    networks:
      - reviewer-service-net
    restart: "no"

  reviewer-service:
    container_name: reviewer-service
    build:
      context: .
      dockerfile: Dockerfile
    image: reviewer-service
    ports:
      - "${HTTP_PORT}:${HTTP_PORT}"
    depends_on:
      migrate:
        condition: service_completed_successfully
    entrypoint: [ "/app/reviewer-service" ]
    command: [ "--config_path=config/prod.env"]
    networks:
      - reviewer-service-net
